language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
before_script: 
  # - sudo apt-get install python-clearsilver
  - "svn --quiet checkout http://googleappengine.googlecode.com/svn/trunk/python ."
  - "la -la"
  - "pwd"
# command to run tests
script: python tests/test_main.py