language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
script: "svn checkout http://googleappengine.googlecode.com/svn/trunk/python ."
# command to run tests
script: nosetests