application: dcputoolchain-module-site
version: 1-0046
runtime: python27
api_version: 1
threadsafe: no

builtins:
- appstats: on
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /xy/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /spec.*
  script: spec.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
