application: dcputoolchain-module-site
version: 1-0057
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- appstats: on
- remote_api: on

libraries:
- name: django
  version: "latest"

- name: webapp2
  version: "latest"

- name: webob
  version: "latest"

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /xy/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /spec.*
  script: spec.app

- url: .*
  script: main.app
